"""empty message

Revision ID: 96892a9ef7a7
Revises: 
Create Date: 2022-07-12 09:53:23.544689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96892a9ef7a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mail_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mail', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mail')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mail_user')
    # ### end Alembic commands ###
